### ISSUE TITLE
non www redirect to www

### ISSUE THREAD

**Issue by willsilvano** [ambientum/ambientum#117]
Hello @hernandev !

Is there any way to configure the http://myapp.com to redirect to http://www.myapp.com?

Thanks!

**Comment by hernandev** [comment]
https://github.com/codecasts/codecasts/blob/develop/app/Units/Core/Http/Middleware/RedirectIfWrongUrlOrProtocol.php

Use this as base, make a middleware.

for nginx based redirect, only customizing the image itself

**Comment by willsilvano** [comment]
Thanks!!
