### ISSUE TITLE
Como faço para conectar a banco de dados SQL?

### ISSUE THREAD

**Issue by devthiagolino** [ambientum/ambientum#136]
Qual driver mais indicado?
há vários dias tento instalar o sqlsrv e tenho problemas, me indicaram o freetds, como faço para carregar o driver pdo_odbc automaticamente utilizando essa imagem?

**Comment by henriquegomes6** [comment]
Nas imagens que eu uso para conectar no SqlServer

` 
set -x \
    && apt-get update \
    && apt-get install -y librabbitmq-dev libssh-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxml2-dev libsybdb5 freetds-dev locales gnupg2 apt-transport-https \
    && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/ \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) soap opcache pdo_dblib gd pdo_mysql bcmath sockets \
    && pecl install amqp redis sqlsrv-5.2.0 pdo_sqlsrv-5.2.0 \
    && docker-php-ext-enable amqp redis sqlsrv pdo_sqlsrv \
    && rm -rf /var/lib/apt/lists/* \
    && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
`

**Comment by devthiagolino** [comment]
@henriquegomes6 , onde tu inclui esse código?

**Comment by henriquegomes6** [comment]
você pode tentar algo do tipo, talvez você tenha adaptar os comandos para funcionar na nessa imagem, pois a imagem que estou usando de exemplo é a direto do php

FROM php:7.2-fpm
set -x \
    && apt-get update \
    && apt-get install -y librabbitmq-dev libssh-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxml2-dev libsybdb5 freetds-dev locales gnupg2 apt-transport-https \
    && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/ \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) soap opcache pdo_dblib gd pdo_mysql bcmath sockets \
    && pecl install amqp redis sqlsrv-5.2.0 pdo_sqlsrv-5.2.0 \
    && docker-php-ext-enable amqp redis sqlsrv pdo_sqlsrv \
    && rm -rf /var/lib/apt/lists/* \
    && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

**Comment by devthiagolino** [comment]
entendi... vou tentar aqui

**Comment by devthiagolino** [comment]
fiz assim e funcionou:

FROM ambientum/php:7.3-nginx
USER root
RUN set -x \
    # install the build pre-requisites.
    && apk add --no-cache --virtual .build-deps autoconf file g++ make pkgconf re2c php7-dev unixodbc-dev libmcrypt-dev \
    # install mssql drivers
    && curl https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.5.1.1-1_amd64.apk -O \
    && curl https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.5.1.2-1_amd64.apk -O \
    && apk add --allow-untrusted msodbcsql17_17.5.1.1-1_amd64.apk \
    && apk add --allow-untrusted mssql-tools_17.5.1.2-1_amd64.apk \
    # at the mssql-tools binary to the path.
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc \
    && /bin/bash -c "source ~/.bashrc" \
    # install the pecl extensions.
    && pecl install mcrypt-1.0.2 \
    && pecl install pdo_sqlsrv \
    && pecl install sqlsrv \
    && pecl install igbinary \
    && pecl install msgpack \
    # enable the extensions.
    && echo extension=mcrypt.so > /etc/php7/conf.d/20-mcrypt.ini \
    && echo extension=pdo_sqlsrv.so > /etc/php7/conf.d/30-pdo_sqlsrv.ini \
    && echo extension=sqlsrv.so > /etc/php7/conf.d/20-sqlsrv.ini \
    && echo extension=igbinary.so > /etc/php7/conf.d/20-igbinary.ini \
    && echo extension=msgpack.so > /etc/php7/conf.d/20-msgpack.ini \
    # locale workaround.
    && export LC_ALL=C \
    # perform image cleanup.
    && apk del .build-deps \
    && rm msodbcsql17_17.5.1.1-1_amd64.apk \
    && rm mssql-tools_17.5.1.2-1_amd64.apk
