### ISSUE TITLE
Bump up to Alpine 3.14

### ISSUE THREAD

**Issue by Sevenlive** [ambientum/ambientum#149]
Hey, i just came across that the EoL of Alpine 3.11 is starting to hit us. The Date is the 01 November 2021. I would suggest switching to the latest Version 3.14. If you want, i can do a PR to fix that problem.  

[https://alpinelinux.org/releases/](https://alpinelinux.org/releases/)

**Comment by hernandev** [comment]
most of the images are being updated, mainly it depends on PHP version
